//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasGYG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReservasGYG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYG_logo_blanco90x90 {
            get {
                object obj = ResourceManager.GetObject("GYG_logo_blanco90x90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYG_logo_naranja_265x265 {
            get {
                object obj = ResourceManager.GetObject("GYG_logo_naranja_265x265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;¡Hoy es el gran día de tu actividad! &lt;/b&gt;
        ///
        ///Te recuerdo que si te desplazas a la playa de Maro (en Nerja) en taxi, el taxi puede llevarte hasta cerca de la playa, si vas en tu propio vehículo tendrás que aparcarlo en algunos de los aparcamientos disponibles en el pueblo de Maro o en el de las Cuevas de Nerja. Pero como estamos en temporada alta, no habrá mucho sitio donde aparcar, por tanto, calcula bien el tiempo que necesitas para llegar a la playa de maro &lt;b&gt;15 minutos antes de la hora de la activida [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hoy_es_el_dia_txt {
            get {
                return ResourceManager.GetString("Hoy_es_el_dia_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMATION OF INTEREST*&lt;/b&gt;
        ///
        ///
        ///&lt;b&gt;*LOCATION*&lt;/b&gt;
        ///Location on Google Maps of *Maro Beach* https://goo.gl/wbLLFd
        ///(*NOT Caleta de Maro, donâ€™t confuse the beaches*.)
        ///
        ///
        ///This would be (approximately) the place to park your car and take the bus down to Maro beach.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANT*&lt;/b&gt;:
        ///Remember that you must be at the companyâ€™s counter (Maro Kayak Nerja, which is right when you arrive at the beach) &lt;b&gt;*15 minutes before the activityâ€™s departure time*&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_EN_09_30_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_EN_09.30_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMATION OF INTEREST*&lt;/b&gt;
        ///
        ///
        ///&lt;b&gt;*LOCATION*&lt;/b&gt;
        ///Location on Google Maps of *Maro Beach* https://goo.gl/wbLLFd
        ///(*NOT Caleta de Maro, don’t confuse the beaches*.)
        ///
        ///
        ///This would be (approximately) the place to park your car and take the bus down to Maro beach.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANT*&lt;/b&gt;:
        ///Remember that you must be at the company’s counter (Maro Kayak Nerja, which is right when you arrive at the beach) &lt;b&gt;*15 minutes before the activity’s departure time*&lt;/b&gt; if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_EN_10_30_11_00_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_EN_10.30_11.00_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMATION OF INTEREST*&lt;/b&gt;
        ///
        ///
        ///&lt;b&gt;*LOCATION*&lt;/b&gt;
        ///Location on Google Maps of *Maro Beach* https://goo.gl/wbLLFd
        ///(*NOT Caleta de Maro, don’t confuse the beaches*.)
        ///
        ///
        ///This would be (approximately) the place to park your car and take the bus down to Maro beach.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANT*&lt;/b&gt;:
        ///Remember that you must be at the company’s counter (Maro Kayak Nerja, which is right when you arrive at the beach) &lt;b&gt;*15 minutes before the activity’s departure time*&lt;/b&gt; if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_EN_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_EN_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMACIÓN DE INTERÉS*&lt;/b&gt;
        ///
        ///
        ///
        ///&lt;b&gt;*LOCALIZACIÓN*&lt;/b&gt;
        ///Ubicación en Google Maps de la &lt;b&gt;*Playa de Maro*&lt;/b&gt;
        ///https://goo.gl/wbLLFd
        ///(&lt;b&gt;*NO ES &quot;Caleta de Maro&quot;, no te confundas de playa*&lt;/b&gt;.)
        ///
        ///
        ///Este sería (aproximadamente) el sitio donde dejar el coche y poder tomar el bus de bajada a la playa de Maro.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANTE*:&lt;/b&gt;
        ///Recuerda que debes estar en el mostrador de la empresa (Maro Kayak Nerja, que está justo cuando llegas a la playa) &lt;b&gt;*15 minuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_ES_09_30 {
            get {
                return ResourceManager.GetString("IMPORTANTE_ES_09.30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMACIÓN DE INTERÉS*&lt;/b&gt;
        ///
        ///
        ///
        ///&lt;b&gt;*LOCALIZACIÓN*&lt;/b&gt;
        ///Ubicación en Google Maps de la &lt;b&gt;*Playa de Maro*&lt;/b&gt;
        ///https://goo.gl/wbLLFd
        ///(&lt;b&gt;*NO ES &quot;Caleta de Maro&quot;, no te confundas de playa*&lt;/b&gt;.)
        ///
        ///
        ///Este sería (aproximadamente) el sitio donde dejar el coche y poder tomar el bus de bajada a la playa de Maro.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANTE*:&lt;/b&gt;
        ///Recuerda que debes estar en el mostrador de la empresa (Maro Kayak Nerja, que está justo cuando llegas a la playa) &lt;b&gt;*15 minuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_ES_10_30_11_00_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_ES_10.30_11.00_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMACIÓN DE INTERÉS*&lt;/b&gt;
        ///
        ///
        ///
        ///&lt;b&gt;*LOCALIZACIÓN*&lt;/b&gt;
        ///Ubicación en Google Maps de la &lt;b&gt;*Playa de Maro*&lt;/b&gt;
        ///https://goo.gl/wbLLFd
        ///(&lt;b&gt;*NO ES &quot;Caleta de Maro&quot;, no te confundas de playa*&lt;/b&gt;.)
        ///
        ///
        ///Este sería (aproximadamente) el sitio donde dejar el coche y poder tomar el bus de bajada a la playa de Maro.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANTE*:&lt;/b&gt;
        ///Recuerda que debes estar en el mostrador de la empresa (Maro Kayak Nerja, que está justo cuando llegas a la playa) &lt;b&gt;*15 minuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_ES_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_ES_txt", resourceCulture);
            }
        }
    }
}
