//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasGYG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReservasGYG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola, este mensaje es para informarte que la previsión del mar para el día de tu actividad indica que habrá pequeñas olas.
        ///
        ///*Tu actividad sigue adelante*, pero como habrá un poco de movimiento, te avisamos solamente en caso que tú o alguien de tu grupo se suela marear, para darte la oportunidad de cambiar la reserva para otra fecha.
        ///
        ///Si no puedes cambiar para otra fecha y no quieres arriesgarte a venir, no hay problema, te devolveremos el dinero pagado.
        ///
        ///Muchas gracias.
        ///
        ///
        ///
        ///
        ///Hi, this message is to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Alerta1_es_en {
            get {
                return ResourceManager.GetString("Alerta1_es_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CleanData {
            get {
                object obj = ResourceManager.GetObject("CleanData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Si tienes problemas para ver las fotos, intenta abrir el enlace nuevamente y si aún así no te funciona, 
        ///por favor responde a este correo o mándame &lt;b&gt;un mensaje de WhatsApp al +34 645 76 16 89&lt;/b&gt; indicando tu nombre y el número de la reserva
        ///y te volveré a mandar el enlace o buscaré una solución para que tengas tus fotos.
        ///
        ///&lt;b&gt;&lt;small&gt;Si no me facilitas esos datos, sea por WhatsApp o email, puede que tarde en responderte.&lt;/small&gt;&lt;/b&gt;
        ///
        ///
        ///
        ///If you have trouble viewing the photos, try opening the link  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fotos_ruta {
            get {
                return ResourceManager.GetString("Fotos_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYG_logo_blanco90x90 {
            get {
                object obj = ResourceManager.GetObject("GYG_logo_blanco90x90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYG_logo_naranja_265x265 {
            get {
                object obj = ResourceManager.GetObject("GYG_logo_naranja_265x265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;¡Hoy es el gran día de tu actividad! &lt;/b&gt;
        ///
        ///&lt;b&gt;*IMPORTANTE*&lt;/b&gt;
        ///El punto de encuentro es en la playa de Maro (https://goo.gl/wbLLFd).
        ///Te recuerdo que &lt;b&gt;debes estar en el mostrador de la empresa de los kayaks 15 minutos antes de la hora de la actividad&lt;/b&gt;.
        ///Si hay cola, NO la hagas, ve directamente al mostrador e indica que tienes una reserva de ruta.
        ///Si llegas tarde tu reserva se cancelará.
        ///
        ///Los vehículos no pueden ir hasta la playa de Maro (porque es zona protegida) y debes aparcar antes de ir a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hoy_es_el_dia_txt {
            get {
                return ResourceManager.GetString("Hoy_es_el_dia_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMATION OF INTEREST*&lt;/b&gt;
        ///
        ///
        ///&lt;b&gt;*LOCATION*&lt;/b&gt;
        ///Location on Google Maps of *Maro Beach* https://goo.gl/wbLLFd
        ///(*NOT Caleta de Maro, donâ€™t confuse the beaches*.)
        ///
        ///
        ///This would be (approximately) the place to park your car and take the bus down to Maro beach.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANT*&lt;/b&gt;:
        ///Remember that you must be at the companyâ€™s counter (Maro Kayak Nerja, which is right when you arrive at the beach) &lt;b&gt;*15 minutes before the activityâ€™s departure time*&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_EN_09_30_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_EN_09.30_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMATION OF INTEREST*&lt;/b&gt;
        ///
        ///
        ///&lt;b&gt;*LOCATION*&lt;/b&gt;
        ///Location on Google Maps of *Maro Beach* https://goo.gl/wbLLFd
        ///(*NOT Caleta de Maro, don’t confuse the beaches*.)
        ///
        ///
        ///This would be (approximately) the place to park your car and take the bus down to Maro beach.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANT*&lt;/b&gt;:
        ///Remember that you must be at the company’s counter (Maro Kayak Nerja, which is right when you arrive at the beach) &lt;b&gt;*15 minutes before the activity’s departure time*&lt;/b&gt; if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_EN_10_30_11_00_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_EN_10.30_11.00_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMATION OF INTEREST*&lt;/b&gt;
        ///
        ///
        ///&lt;b&gt;*LOCATION*&lt;/b&gt;
        ///Location on Google Maps of *Maro Beach* https://goo.gl/wbLLFd
        ///(*NOT Caleta de Maro, don’t confuse the beaches*.)
        ///
        ///
        ///This would be (approximately) the place to park your car and take the bus down to Maro beach.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANT*&lt;/b&gt;:
        ///Remember that you must be at the company’s counter (Maro Kayak Nerja, which is right when you arrive at the beach) &lt;b&gt;*15 minutes before the activity’s departure time*&lt;/b&gt; if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_EN_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_EN_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMACIÓN DE INTERÉS*&lt;/b&gt;
        ///
        ///
        ///
        ///&lt;b&gt;*LOCALIZACIÓN*&lt;/b&gt;
        ///Ubicación en Google Maps de la &lt;b&gt;*Playa de Maro*&lt;/b&gt;
        ///https://goo.gl/wbLLFd
        ///(&lt;b&gt;*NO ES &quot;Caleta de Maro&quot;, no te confundas de playa*&lt;/b&gt;.)
        ///
        ///
        ///Este sería (aproximadamente) el sitio donde dejar el coche y poder tomar el bus de bajada a la playa de Maro.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANTE*:&lt;/b&gt;
        ///Recuerda que debes estar en el mostrador de la empresa (Maro Kayak Nerja, que está justo cuando llegas a la playa) &lt;b&gt;*15 minuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_ES_09_30 {
            get {
                return ResourceManager.GetString("IMPORTANTE_ES_09.30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMACIÓN DE INTERÉS*&lt;/b&gt;
        ///
        ///
        ///
        ///&lt;b&gt;*LOCALIZACIÓN*&lt;/b&gt;
        ///Ubicación en Google Maps de la &lt;b&gt;*Playa de Maro*&lt;/b&gt;
        ///https://goo.gl/wbLLFd
        ///(&lt;b&gt;*NO ES &quot;Caleta de Maro&quot;, no te confundas de playa*&lt;/b&gt;.)
        ///
        ///
        ///Este sería (aproximadamente) el sitio donde dejar el coche y poder tomar el bus de bajada a la playa de Maro.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANTE*:&lt;/b&gt;
        ///Recuerda que debes estar en el mostrador de la empresa (Maro Kayak Nerja, que está justo cuando llegas a la playa) &lt;b&gt;*15 minuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_ES_10_30_11_00_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_ES_10.30_11.00_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;*INFORMACIÓN DE INTERÉS*&lt;/b&gt;
        ///
        ///
        ///
        ///&lt;b&gt;*LOCALIZACIÓN*&lt;/b&gt;
        ///Ubicación en Google Maps de la &lt;b&gt;*Playa de Maro*&lt;/b&gt;
        ///https://goo.gl/wbLLFd
        ///(&lt;b&gt;*NO ES &quot;Caleta de Maro&quot;, no te confundas de playa*&lt;/b&gt;.)
        ///
        ///
        ///Este sería (aproximadamente) el sitio donde dejar el coche y poder tomar el bus de bajada a la playa de Maro.
        ///https://goo.gl/maps/ZfNzUsfkCN1q8iD47
        ///
        ///
        ///
        ///&lt;b&gt;*IMPORTANTE*:&lt;/b&gt;
        ///Recuerda que debes estar en el mostrador de la empresa (Maro Kayak Nerja, que está justo cuando llegas a la playa) &lt;b&gt;*15 minuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMPORTANTE_ES_txt {
            get {
                return ResourceManager.GetString("IMPORTANTE_ES_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;¡Mañana es el gran día de tu actividad!&lt;/b&gt;
        ///
        ///&lt;b&gt;*IMPORTANTE*&lt;/b&gt;
        ///El punto de encuentro es en la playa de Maro (https://goo.gl/wbLLFd).
        ///Te recuerdo que &lt;b&gt;debes estar en el mostrador de la empresa de los kayaks 15 minutos antes de la hora de la actividad&lt;/b&gt;.
        ///Si hay cola, NO la hagas, ve directamente al mostrador e indica que tienes una reserva de ruta.
        ///Si llegas tarde tu reserva se cancelará.
        ///
        ///Los vehículos no pueden ir hasta la playa de Maro (porque es zona protegida) y debes aparcar antes de ir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mañana_es_el_dia {
            get {
                return ResourceManager.GetString("Mañana_es_el_dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
